New sync workflow

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -16,15 +16,15 @@ jobs:
           fetch-depth: 0
       
       - name: List all branches
-        run: git branch -a
+        run: echo "BRANCHES=$(git branch -r | grep -v HEAD | grep -v main | sed 's/origin\///g')" >> $GITHUB_ENV
         id: branches
       - name: Merge changes from main
         run: |
-          arr=($(echo ${{ steps.branches.outputs.stdout }} | tr ' ' '\n'))
+          arr=($(echo ${{ steps.branches.outputs.BRANCHES }} | tr ' ' '\n'))
           for i in "${arr[@]}"
           do
             git checkout $i
-            git merge main
+            git merge main --no-edit --no-ff || echo "Merge failed for $i"
           done
       - name: Push all changes
         run: git push origin --all
